//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by V_Klay.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDM_HELPWND                     0x0020
#define IDD_ABOUTBOX                    100
#define IDD_V_KLAY_DIALOG               102
#define CG_IDD_PROGRESS                 103
#define IDD_LAYOUT_PROPPAGE             106
#define IDD_PATCH_PROPPAGE              132
#define IDD_FLASHER_PROPPAGE            134
#define IDD_OPTIONS_DIALOG              137
#define IDR_PATCH_MENU                  138
#define IDD_OPTIONS_ADVANCED_DIALOG     138
#define ID__CUT                         139
#define ID__COPY                        140
#define IDR_TOOLS_OPTIONS_MENU          140
#define ID__PASTE                       141
#define ID__REDO                        142
#define IDS_STRING144                   144
#define IDI_VKLAY                       146
#define IDI_VKLAY_FILES                 147
#define IDI_VKLAY_FOLDER                148
#define IDI_VKLAY_SETUP                 149
#define IDI_TOOLS_OPTIONS               152
#define ID_LAYOUT_EXTLAY_READ_FULLFLASH 153
#define ID_LAYOUT_EXTLAY_USE_FULLFLASH  154
#define IDI_TOOL_EXT1                   154
#define ID_LAYOUT_EXTLAY_OPTIONS        155
#define IDI_TOOL_EXTPIC                 157
#define IDI_TOOL_EXTLAY                 158
#define IDI_TOOL_EXT2                   159
#define IDI_TOOL_EXT3                   160
#define ID_TOOLS_READFF                 162
#define ID_TOOLS_USEFF                  163
#define ID_TOOLS_ONLY_RUN               164
#define ID_TOOLS_SHOW_OPTIONS           165
#define IDI_TOOL_EXTFNT                 166
#define IDR_ACCELERATOR                 167
#define IDI_OPEN                        168
#define IDI_NEW                         169
#define ID_PATCH_DATA_COLOR             169
#define IDI_SAVE                        170
#define ID_PATCH_DATA_PASTETEXT         170
#define IDI_NEW2                        171
#define IDI_APPEND                      171
#define ID_PATCH_DATA_FONT              171
#define ID_PATCH_DATA_BACKCOLOR         172
#define IDI_RESET                       172
#define ID_Menu                         173
#define IDI_SAVE_AS                     173
#define ID_PATCH_DATA_FIND              174
#define IDI_REOPEN                      174
#define ID_PATCH_DATA_REPLACE           175
#define IDR_ACCELERATOR_PATCH_PAGE      176
#define IDD_CONSOLE_DIALOG              178
#define IDI_TOOL_EXTFFED                179
#define IDD_HEX_VIEW_DIALOG             180
#define IDC_HELPWND                     200
#define IDC_FLASH_BROWSE                1000
#define IDC_FLASH_FNAME                 1001
#define ID_UPDATE                       1002
#define IDC_BIG_KEY1                    1003
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_TEXT_KEY1                   1004
#define IDC_INI_BROWSE                  1005
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_INI_FNAME                   1006
#define IDC_INI_COMMENTS                1006
#define ID_ABOUT                        1007
#define ID_FLASH_LOAD                   1008
#define ID_ABOUT2                       1008
#define ID_OPTIONS                      1008
#define IDC_KEYS_LOAD                   1009
#define IDC_KEYS_SAVE                   1010
#define IDC_BUTTON1                     1011
#define IDC_TOOL_EXTLAY_PATH_BROWSE     1011
#define IDC_EMAIL                       1011
#define ID_PATCH_APPLY_TEST             1011
#define IDC_FLASH_FROM                  1012
#define IDC_TOOL_EXTPIC_PATH_BROWSE     1012
#define IDC_WEB                         1012
#define ID_PATCH_UNDO_TEST              1012
#define IDC_FLASH_SIZE                  1013
#define IDC_TOOL_EXT1_PATH_BROWSE       1013
#define IDC_TAB                         1014
#define IDC_TOOL_EXT2_PATH_BROWSE       1014
#define IDC_CALC_LOAD                   1015
#define IDC_TOOLS_OPTIONS               1015
#define IDC_TOOL_EXT3_PATH_BROWSE       1015
#define IDC_CALC_SAVE                   1016
#define IDC_TOOL_EXTPIC                 1016
#define IDC_TOOL_EXTFNT_PATH_BROWSE     1016
#define IDC_CALC_LIST1                  1017
#define IDC_TOOL_EXTFNT                 1017
#define IDC_OPTIONS_ADVANCED            1017
#define IDC_CALC_LIST_CODE1             1018
#define IDC_TOOL_EXT1                   1018
#define IDC_TOOL_TMP_PATH_BROWSE        1018
#define ID_PATCH_UNDO                   1019
#define IDC_WEB2                        1019
#define ID_PATCH_APPLY                  1020
#define IDC_TOOL_EXT2                   1020
#define IDC_PATCH_LOAD                  1021
#define IDC_PATCH_SAVE                  1022
#define IDC_TOOL_EXT3                   1022
#define IDC_PATCH_APPEND                1023
#define IDC_INI_STATIC                  1024
#define IDC_PATCH_NEW                   1024
#define IDC_INI_AUTHOR_STATIC           1024
#define IDC_SELECT_PHONE                1025
#define IDC_PATCH_SAVE_AS               1025
#define IDC_SELECT_FILE                 1026
#define IDC_PATCH_RELOAD                1026
#define IDC_FLASH_FROM_TEXT             1027
#define IDC_FLASH_SIZE_TEXT             1028
#define IDC_BIG_CODE_KEY1               1029
#define IDC_FLASH_FILE_TEXT             1029
#define IDC_PHONES_LIST_TEXT            1030
#define IDC_CALC_LIST2                  1031
#define IDC_PHONES_LIST                 1031
#define IDC_CALC_LIST_CODE2             1032
#define IDC_PHONE_PORTS_LIST_TEXT       1032
#define IDC_CALC_LIST3                  1033
#define IDC_PHONE_PORTS_LIST            1033
#define IDC_SMALL_KEY1                  1034
#define IDC_CALC_LIST_CODE3             1034
#define IDC_PHONE_FLASH_INFO            1034
#define IDC_SMALL_CODE_KEY1             1035
#define IDC_CALC_LIST4                  1035
#define IDC_FLASHER_FROM                1035
#define IDC_PHONE_BAUDS_LIST            1035
#define IDC_TEXT_KEY2                   1036
#define IDC_CALC_LIST_CODE4             1036
#define IDC_FLASHER_SIZE                1036
#define IDC_PHONE_BAUDS_LIST_TEXT       1036
#define IDC_BIG_KEY2                    1037
#define IDC_CALC_LIST5                  1037
#define ID_FLASHER_MEMORY_LOAD          1037
#define IDC_DONATE_DETAILS              1037
#define IDC_BIG_CODE_KEY2               1038
#define IDC_CALC_LIST_CODE5             1038
#define ID_FLASHER_MEMORY_WRITE         1038
#define IDC_SMALL_KEY2                  1039
#define IDC_CALC_LIST6                  1039
#define IDC_FLASHER_FILE_LOAD           1039
#define IDC_SMALL_CODE_KEY2             1040
#define IDC_CALC_LIST_CODE6             1040
#define IDC_FLASHER_FILE_WRITE          1040
#define IDC_TEXT_KEY3                   1041
#define IDC_CALC_LIST7                  1041
#define IDC_PHONE_RESET                 1041
#define IDC_BUFFER_OFFSET               1041
#define IDC_BIG_KEY3                    1042
#define IDC_CALC_LIST_CODE7             1042
#define IDC_COPYRIGHT_TEXT              1042
#define IDC_V_COPYRIGHT_TEXT            1042
#define IDC_ABOUT_TEXT                  1042
#define IDC_PHONE_QUERY_INFO            1042
#define IDC_FLASHER_MEMORY_RESTORE_BOOTCORE 1042
#define IDC_BIG_CODE_KEY3               1043
#define IDC_CALC_LIST8                  1043
#define IDC_FLASHER_MEMORY_MAP          1043
#define IDC_SMALL_KEY3                  1044
#define IDC_CALC_LIST_CODE8             1044
#define IDC_BUFFER_SIZE                 1044
#define IDC_SMALL_CODE_KEY3             1045
#define IDC_CUR_LINE                    1045
#define IDC_BUFFER_LAST_FROM            1045
#define IDC_BIG_KEY4                    1046
#define IDC_CUR_COL                     1046
#define IDC_BIG_CODE_KEY4               1047
#define IDC_SMALL_KEY4                  1048
#define IDC_V_ICON                      1048
#define IDC_SMALL_CODE_KEY4             1049
#define IDC_DESCRIPTION_TEXT            1049
#define IDC_BIG_KEY5                    1050
#define IDC_BIG_CODE_KEY5               1051
#define IDC_SMALL_KEY5                  1052
#define IDC_CHECK1                      1052
#define IDC_WARNING_MSG_DISABLE         1052
#define IDC_COM_RTS                     1052
#define IDC_SMALL_CODE_KEY5             1053
#define IDC_EDIT1                       1053
#define IDC_AUTOIGN_ENABLE              1053
#define IDC_PATCHER_FONT_SIZE           1053
#define IDC_TEXT                        1053
#define IDC_HEX_EDIT                    1053
#define IDC_BIG_KEY6                    1054
#define IDC_COMBO1                      1054
#define IDC_LOCALE                      1054
#define IDC_BIG_CODE_KEY6               1055
#define IDC_WORKWITH_STATIC             1055
#define IDC_LANG                        1055
#define IDC_SMALL_KEY6                  1056
#define IDC_PATCHER_TAB_STATIC          1056
#define IDC_SMALL_CODE_KEY6             1057
#define IDC_PATCHER_CODEPAGE_STATIC     1057
#define IDC_TEXT_KEY4                   1058
#define IDC_LANG_STATIC2                1058
#define IDC_LANG_STATIC                 1058
#define IDC_TEXT_KEY5                   1059
#define IDC_GENERAL_STATIC              1059
#define IDC_TEXT_KEY6                   1060
#define IDC_LANG_AUTHOR_STATIC          1060
#define IDC_BIG_KEY7                    1061
#define IDC_LANG_AUTHOR                 1061
#define IDC_BIG_CODE_KEY7               1062
#define IDC_MEMORY_STATIC               1062
#define IDC_RTF_WARNING_MSG_DISABLE     1062
#define IDC_SMALL_KEY7                  1063
#define IDC_FROM_STATIC                 1063
#define IDC_TOOL_EXTLAY_PATH_STATIC     1063
#define IDC_SMALL_CODE_KEY7             1064
#define IDC_MEMORY_SIZE_STATIC          1064
#define IDC_TOOL_EXTPIC_PATH_STATIC     1064
#define IDC_BIG_KEY8                    1065
#define IDC_BUFFER_STATIC               1065
#define IDC_TOOL_EXT1_PATH_STATIC       1065
#define IDC_BIG_CODE_KEY8               1066
#define IDC_BUFFER_OFFSET_STATIC        1066
#define IDC_TOOL_EXT2_PATH_STATIC       1066
#define IDC_SMALL_KEY8                  1067
#define IDC_BUFFER_SIZE_STATIC          1067
#define IDC_TOOL_EXT3_PATH_STATIC       1067
#define IDC_SMALL_CODE_KEY8             1068
#define IDC_BUFFER_NOTE_STATIC          1068
#define IDC_TOOL_EXTFNT_PATH_STATIC     1068
#define IDC_BIG_KEY9                    1069
#define IDC_OPERATIONS_STATIC           1069
#define IDC_PATCHER_FONT_SIZE_STATIC    1069
#define IDC_BIG_CODE_KEY9               1070
#define IDC_READ_STATIC                 1070
#define IDC_TOOL_TMP_PATH_STATIC        1070
#define IDC_SMALL_KEY9                  1071
#define IDC_SAVE_STATIC                 1071
#define IDC_PASTE_KEYS_SWAP             1071
#define IDC_SMALL_CODE_KEY9             1072
#define IDC_OPEN_STATIC                 1072
#define IDC_TEXT_KEY7                   1073
#define IDC_WRITE_STATIC                1073
#define IDC_TEXT_KEY8                   1074
#define IDC_TEXT_KEY9                   1075
#define IDC_BIG_KEYS                    1076
#define IDC_BIG_CODE_KEYS               1077
#define IDC_SMALL_KEYS                  1078
#define IDC_SMALL_CODE_KEYS             1079
#define IDC_BIG_KEY0                    1080
#define IDC_BIG_CODE_KEY0               1081
#define IDC_SMALL_KEY0                  1082
#define IDC_SMALL_CODE_KEY0             1083
#define IDC_BIG_KEYG                    1084
#define IDC_BIG_CODE_KEYG               1085
#define IDC_SMALL_KEYG                  1086
#define IDC_SMALL_CODE_KEYG             1087
#define IDC_TEXT_KEYS                   1088
#define IDC_FINDDLG_FIND_WHAT_TEXT      1088
#define IDC_REPLACEDLG_FIND_WHAT_TEXT   1088
#define IDC_TEXT_KEY0                   1089
#define IDC_REPLACEDLG_REPLACE_WITH_TEXT 1089
#define IDC_TEXT_KEYG                   1090
#define IDC_INI_TITLE_STATIC            1091
#define IDC_SYMBOLS1_STATIC             1092
#define IDC_CODES1_STATIC               1093
#define IDC_SYMBOLS2_STATIC             1094
#define IDC_SYMBOLS3_STATIC             1095
#define IDC_CODES2_STATIC               1096
#define IDC_CODES3_STATIC               1097
#define IDC_BIG1_STATIC                 1098
#define IDC_BIG2_STATIC                 1099
#define IDC_BIG3_STATIC                 1100
#define IDC_BIG4_STATIC                 1101
#define IDC_SMALL1_STATIC               1102
#define IDC_SMALL2_STATIC               1103
#define IDC_SMALL3_STATIC               1104
#define IDC_SMALL4_STATIC               1105
#define IDC_DATA_FORMAT_STATIC          1106
#define IDC_COLUMN_STATIC               1107
#define IDC_LINE_STATIC                 1108
#define IDC_RESIZE_MARKER_STATIC        1109
#define IDC_INI_AUTHOR                  1110
#define IDC_INI_PHONE                   1111
#define IDC_RESIZE_MARKER_STATIC2       1111
#define IDC_RESIZE_MARKER2_STATIC       1111
#define IDC_INI_NAME                    1112
#define IDC_INI_COMMENTS_STATIC         1113
#define IDC_TOOL_EXTLAY_PATH            1114
#define IDC_TOOL_EXTLAY                 1115
#define IDC_TOOL_EXTPIC_PATH            1115
#define IDC_TOOL_EXT1_PATH              1116
#define IDC_TOOL_EXT2_PATH              1117
#define IDC_TOOL_EXT3_PATH              1118
#define IDC_TOOL_EXTFNT_PATH            1119
#define IDC_AUTOIGN_SIMPLE              1120
#define IDC_AUTOIGN_AUTO                1120
#define IDC_TOOL_TMP_PATH               1120
#define IDC_RADIO2                      1121
#define IDC_AUTOIGN_ORIG                1121
#define IDC_AUTOIGN_SIMPL               1121
#define IDC_AUTOIGN_TYPE_TEXT           1122
#define IDC_PATCH_DATA                  1123
#define IDC_AUTOIGN_ORIGSIE             1123
#define IDC_WEB_TEXT                    1123
#define ID_PATCH_DATA_COPY              1124
#define IDC_EMAIL_TEXT                  1124
#define ID_PATCH_DATA_CUT               1125
#define ID_PATCH_DATA_PASTE             1126
#define IDC_ADVUSER_STATIC              1126
#define ID_PATCH_DATA_UNDO              1127
#define IDC_COM_SIMPLE_MODE             1127
#define ID_PATCH_DATA_REDO              1128
#define IDC_COMPATIBILITY_WARN          1128
#define ID_PATCH_DATA_SELECT_ALL        1129
#define IDC_COMPATIBILITY_STATIC        1129
#define IDC_PHONE_LDRSTATE              1129
#define ID_PATCH_DATA_DELETE            1130
#define IDC_ADVUSER_IGNORE_CANCEL_REPAIR_PATCH 1130
#define IDC_PATCHER_FONT_SIZE_SPIN      1130
#define IDC_ADVUSER_IGNORE_NO_OLD       1131
#define IDC_ADVUSER_REPAIR_PATCH_TEXT_SIMPLE 1132
#define IDC_COM_DTR                     1133
#define IDC_ADVUSER_ENBLE_BOOTCORE_WRITING 1134
#define IDC_DONATE_LINK                 1135
#define IDC_BUFFER_VIEW                 1136
#define IDC_TOOL_EXTLAY_ARG             1150
#define IDC_TOOL_EXTPIC_ARG             1151
#define IDC_TOOL_EXTFNT_ARG             1152
#define IDC_TOOL_EXT1_ARG               1153
#define IDC_TOOL_EXT2_ARG               1154
#define IDC_TOOL_EXT3_ARG               1155
#define IDC_TOOL_EXTLAY_ARG_INS         1156
#define IDC_TOOL_EXTPIC_ARG_INS         1157
#define IDC_TOOL_EXTFNT_ARG_INS         1158
#define IDC_TOOL_EXT1_ARG_INS           1159
#define IDC_TOOL_EXT2_ARG_INS           1160
#define IDC_TOOL_EXT3_ARG_INS           1161
#define IDC_BUFFER_LAST_FROM_STATIC     1162
#define IDD_FINDDLG                     1540
#define IDD_REPLACEDLG                  1541
#define ID_SWITCH_PANEL                 32771
#define ID_PATCH_DATA_COMMENT           32777
#define ID_PATCH_DATA_UNCOMMENT         32778
#define IDC_STATUS_TEXT                 61975

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
